# Generated by Django 4.0.2 on 2022-03-20 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100, verbose_name='Задача')),
                ('content', models.TextField(blank=True, max_length=300, verbose_name='Информация о задаче')),
                ('data_todo', models.DateField( blank=True,  verbose_name='Дата выполнения')),
                ('is_done', models.BooleanField(default=False, verbose_name='Сделано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todo.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
